name: Maven CI/CD with Cucumber Reports

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Xvfb for headless GUI tests
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Build, test and generate reports
        run: xvfb-run mvn clean verify

#      - name: Upload Surefire Test Reports
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: surefire-reports
#          path: target/surefire-reports

      - name: Upload Cucumber HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-reports
          path: target/cucumber-JVM-reports/cucumber-html-reports
