name: Maven CI/CD

on:
  push:
    branches: [ "**" ]         # Trigger on push to any branch
  pull_request:
    branches: [ "**" ]         # Trigger on PR to any branch

jobs:
  build_and_test:
    name: Build and Test with Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build project with Maven
        run: mvn clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports